POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###

POST http://localhost:8080/item
Content-Type: application/json

{
"category": 1,
"color": 2
}

###

POST http://localhost:8080/item
Content-Type: application/json
Authorization: ADMIN

{
  "category": 1,
  "color": 2
}