POST http://localhost:8080/user
Content-Type: application/json

{
  "login": "login",
  "password": "pass"
}

###

POST http://localhost:8080/item
Content-Type: application/json

{
"category": 1,
"color": 2
}

###

POST http://localhost:8080/item
Content-Type: application/json
Authorization: admin

{
  "category": 1,
  "color": 2
}